/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package container;

import javax.swing.ImageIcon;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author filip
 */
public class TelaCadastro extends javax.swing.JFrame {

    private Usuario usuario;

    public TelaCadastro(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        setLocationRelativeTo(null);
        if (usuario != null) {
            jNomeCadastro.setText(this.usuario.getNome());
            jEmailCadastro.setText(this.usuario.getEmail());
            jCidadeCadastro.setText(this.usuario.getCidade());
            jSenhaCadastro.setText(this.usuario.getSenha());
            jEmailCadastro.setEditable(false);
            jEmailCadastro.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jSplitPane1 = new javax.swing.JSplitPane();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jNomeCadastro = new javax.swing.JTextField();
        jEmailCadastro = new javax.swing.JTextField();
        jCidadeCadastro = new javax.swing.JTextField();
        jNome1 = new javax.swing.JLabel();
        jEmail1 = new javax.swing.JLabel();
        jCidade1 = new javax.swing.JLabel();
        jSenha1 = new javax.swing.JLabel();
        jConSenha1 = new javax.swing.JLabel();
        jSenhaCadastro = new javax.swing.JPasswordField();
        jSenConCadastro = new javax.swing.JPasswordField();
        jConfirmar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame2.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame2.setVisible(true);

        jNome1.setBackground(new java.awt.Color(204, 255, 204));
        jNome1.setText("Nome:");
        jNome1.setToolTipText("");

        jEmail1.setText("E-mail:");

        jCidade1.setText("Cidade/Estado:");

        jSenha1.setText("Senha:");

        jConSenha1.setText("Confirmar Senha:");

        jConfirmar.setText("Confirmar");
        jConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmarActionPerformed(evt);
            }
        });

        jCancelar.setText("Cancelar");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("Adicionar foto");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jEmail1)
                    .addComponent(jNome1)
                    .addComponent(jCidade1)
                    .addComponent(jSenha1)
                    .addComponent(jConSenha1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(jConfirmar)
                        .addGap(126, 126, 126)
                        .addComponent(jCancelar))
                    .addComponent(jEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCidadeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSenConCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(jNome1)
                        .addGap(17, 17, 17))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(jNomeCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmail1)
                    .addComponent(jEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCidade1)
                    .addComponent(jCidadeCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSenha1)
                    .addComponent(jSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSenConCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConSenha1))
                .addGap(55, 55, 55)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConfirmar)
                    .addComponent(jCancelar))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmarActionPerformed
        if (!jNomeCadastro.getText().trim().isEmpty() && !jEmailCadastro.getText().trim().isEmpty() && !jCidadeCadastro.getText().trim().isEmpty() && !new String(jSenhaCadastro.getPassword()).trim().isEmpty()) {
            if (new String(jSenhaCadastro.getPassword()).equals(new String(jSenConCadastro.getPassword()))) {
                Conexao cn = new Conexao();
                cn.conectar();
                try {
                    if (this.usuario == null) {
                        cn.inserircadastro(jEmailCadastro.getText(), new String(jSenhaCadastro.getPassword()), jNomeCadastro.getText(), jCidadeCadastro.getText());
                        JOptionPane.showMessageDialog(null, "Sucesso");
                        dispose();
                    } else {

                        cn.atualizar(jNomeCadastro.getText(), jCidadeCadastro.getText(), new String(jSenhaCadastro.getPassword()), usuario.getId());
                        JOptionPane.showMessageDialog(null, "Sucesso");
                        dispose();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "não foi possivel cadastrar");
                }

            } else {
                JOptionPane.showMessageDialog(null, "As senhas não são iguais.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Campo em branco.");
        }
    }//GEN-LAST:event_jConfirmarActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        if (this.usuario == null) {
            new TelaInicial().setVisible(true);
        } else {
            new TelaPrincipal(this.usuario).setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_jCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jCancelar;
    private javax.swing.JLabel jCidade1;
    private javax.swing.JTextField jCidadeCadastro;
    private javax.swing.JLabel jConSenha1;
    private javax.swing.JButton jConfirmar;
    private javax.swing.JLabel jEmail1;
    private javax.swing.JTextField jEmailCadastro;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jNome1;
    private javax.swing.JTextField jNomeCadastro;
    private javax.swing.JPasswordField jSenConCadastro;
    private javax.swing.JLabel jSenha1;
    private javax.swing.JPasswordField jSenhaCadastro;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
